host = "0.0.0.0:8080"


users = [
    { openid = "xxx", memos_open_api = "https://demo.usememos.com/api/v1/memo?openId=B0A20B12622CD78F448856BD67F1EF7A" },
    { openid = "kkbt", memos_open_api = "http://192.168.0.107:5230/api/memo?openId=xxxxxxxxxxx" },
]

wechat_r_unkown_user = "é™Œç”Ÿäºº: ${openid}"
wechat_r_default = "ğŸ“© å·²ä¿å­˜"
wechat_r_text = "ğŸ“© å·²ä¿å­˜æ–‡å­—"
wechat_r_image = "ğŸ“© å·²ä¿å­˜å›¾ç‰‡"
wechat_r_voice = "ğŸ“© å·²ä¿å­˜è¯­éŸ³"
wechat_r_location = "ğŸ“© å·²ä¿å­˜ä½ç½®"
wechat_r_link = "ğŸ“© å·²ä¿å­˜é“¾æ¥"
wechat_r_video ="ä¸æ”¯æŒè§†é¢‘æ¶ˆæ¯"
wechat_r_unknown = "æœªçŸ¥ç±»å‹æ¶ˆæ¯"

[wechat]
token = "wechat_token"
appid = "wechat_appid"
secret = "wechat_secret"
